spring.application.name=boardgame-cafe

spring.datasource.url=jdbc:h2:file:./data/boardgamecafe;AUTO_SERVER=TRUE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

spring.thymeleaf.cache=false

boardgamecafe.admin.usuario=${ADMIN_USUARIO:admin}
boardgamecafe.admin.senha=${ADMIN_SENHA:admin123}

server.port=${PORT:8080}